config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: :create
  end
  resources :users, only: [:edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :content
  end

  validates :image, presence: { message: 'を添付してください' }
  
  has_one_attached :image

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end



  private
  def post_params
    params.require(:post).permit(:title, :content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title>Catalk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    

  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Catalk🐈‍⬛</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to current_user.nickname, edit_user_path(current_user), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "投稿", new_post_path, class: "nav-link"%>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: "nav-link"%>
              </li>
              <% end %>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer class="footer bg-secondary text-center text-light p-5 mt-5">
      (c) Cattalkα
    </footer>
  </body>
</html>

app/views/posts/edit.html.erb
<div>
  <div class="col-md-4 offset-md-4">
    <h2 class="text-center pt-5">編集する🐈‍⬛</h2>
    <%= form_with(model:@post, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group" >
        <%= f.file_field :image, placeholder: "ka", class: "form-control" %>
      </div>
      <div class="form_group pt-4 pb-3">
        <%= f.text_field :title, placeholder: "タイトル", class: "form-control" %>
      </div>

      <div class="form-group" >
        <%= f.text_area :content, placeholder: "にゃいようについて書いてくださいNya", rows: 7, class: "form-control" %>
      </div>

      <div class="text-center"> 
        <%= f.submit "変更", class: "btn btn-primary mt-2" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<section class="py-5 text-center container bg-light">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light text-warning">🐈‍⬛ Cattalkへようこそ！🐈‍⬛</h1>
      <p class="lead text-muted">Catalk🐈‍⬛は自分の猫ちゃんの記録を残したり、他の猫好き同士で共有しあったりできるサービスです。（登録するお名前は猫ちゃんのお名前をお勧めしています。）🚨現在スマートフォンで利用する際は横画面でご利用ください🚨</p>
    </div>
  </div>
</section>

<div class="texts-wrapper">
   <div class="contents-title text-center mt-2">
      <h3>投稿一覧</h3>
      <div class="row">
        <% @posts.each do |post| %>
          <div class="col-12 col-md-6 col-lg-4">
            <div class="card m-2">
               <%= image_tag post.image, class:"card-img-top img-rounded img-responsive h-100" %>
               <div class="card-body">
                  <h5 class="card-title"><%= post.title %></h5>
                  <p class="card-text"><%= post.content %></p>
                  
                  <%= link_to "詳細", post_path(post.id), class: 'btn btn-primary' %>
               </div>
            </div>
          </div>
        <% end %>
     </div>
   </div>
 </div> 

app/views/posts/new.html.erb
<div>
  <div class="col-md-4 offset-md-4">
    <h2 class="text-center pt-5">新規投稿🐈‍⬛</h2>
    <%= form_with(model:@post, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group" >
        <%= f.file_field :image, placeholder: "ka", class: "form-control" %>
      </div>
      <div class="form_group pt-4 pb-3">
        <%= f.text_field :title, placeholder: "タイトル", class: "form-control" %>
      </div>

      <div class="form-group" >
        <%= f.text_area :content, placeholder: "内容", rows: 7, class: "form-control" %>
      </div>

      <div class="text-center"> 
        <%= f.submit "投稿", class: "btn btn-primary mt-2" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="texts-wrapper">
  <div class="contents-title text-center mt-2">
    <h3>詳細ページ</h3>
  </div>
</div>
<div class="col-12 col-md-6 col-lg-4">
  <div class="card-deck">
    <div class="card m-2">
      <%= image_tag @post.image, class:"card-img-top img-rounded img-responsive h-100" %>
      <div class="card-body text-center">
        <h5 class="card-title"><%= @post.title %></h5>
        <p class="card-text"><%= @post.content %></p>
        <% if user_signed_in? && current_user.id == @post.user_id %>
        <%= link_to "編集", edit_post_path(@post.id), class: 'btn btn-primary' %>
        <%= link_to "削除", post_path(@post.id), method: :delete, class: 'btn btn-primary' %>
        <% else %>
        <% end %>
      </div>
    </div>
    <div class="card m-2">
      <%= form_with(model: [@post, @comment], local: true) do |f| %>
        <div class="form-group" >
          <%= f.text_area :text, placeholder: "コメントしてね", rows: 2, class: "form-control" %>
        </div>
        <div class="text-center"> 
          <%= f.submit "投稿", class: "btn btn-primary mt-2" %>
        </div>
      <% end %>
      <h5 class="contents-title text-left mt-2">＜コメント一覧＞</h5>
      <% @comments.each do |comment| %>
        <p class="card-text text-left mt-1 ms-1">
          <strong><%= link_to comment.user.nickname, "#" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul> 
  </div> 
<% end %>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Cat🐈‍⬛</h2>
      <h5>登録の変更</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "トップ画面に戻る", root_path, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :お名前%>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>